server:
  port: ${SERVER_PORT:9000}
  address: ${SERVER_HOST:localhost}
  ssl:
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-password: ${SERVER_SSL_KEY_PASSWORD}
    key-alias: ${SERVER_SSL_KEY_ALIAS}
    enabled: ${SERVER_SSL_ENABLED:false}

spring:
  application:
    name: url-shortener
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:url_shortener_app_db}?ssl=${DB_SSL:false}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      pool-name: Hikari
      minimum-idle: ${HIKARI_MIN_IDLE:10}
      maximum-pool-size: ${HIKARI_THREAD_POOL_SIZE:20}
      max-lifetime: ${HIKARI_MAX_LIFETIME:600000}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:2000}
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: ${LIQUIBASE_ENABLED:true}

management:
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: ${METRICS_PROMETHEUS_PUSH_GATEWAY_ENABLED:true}
          base-url: ${METRICS_PROMETHEUS_PUSH_GATEWAY_ADDRESS:http://localhost:9091}
          push-rate: 5s
          username: ${METRICS_PROMETHEUS_PUSH_GATEWAY_USERNAME:${null}}
          password: ${METRICS_PROMETHEUS_PUSH_GATEWAY_PASSWORD:${null}}
          shutdown-operation: push
          job: ${METRICS_PROMETHEUS_PUSH_GATEWAY_JOB_NAME:url-shortener-app}

url-shortener-app:
  url-repository:
    retry-on-save: ${URL_REPOSITORY_RETRY_ON_SAVE:3}
    url-id-length: ${URL_REPOSITORY_URL_ID_LENGTH:8}
    reactor-thread-pool-size: ${URL_REPOSITORY_REACTOR_THREAD_POOL_SIZE:10}
  url-cache:
    type: ${URL_CACHE_TYPE:in_memory}
    properties:
      in-memory-size: ${URL_CACHE_IN_MEMORY_SIZE:1000}
      in-memory-max-valid-duration: ${URL_CACHE_IN_MEMORY_MAX_VALID_DURATION:30s}
      redis-address: ${URL_CACHE_REDIS_ADDRESS:redis://localhost:6379}
      redis-password: ${URL_CACHE_REDIS_PASSWORD:redispassword}
      redis-connection-pool-size: ${URL_CACHE_REDIS_CONNECTION_POOL_SIZE:20}

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    url: "/v3/api-docs"
    path: "/swagger"
    enabled: ${SWAGGER_ENABLED:true}

logging:
  level:
    root: ${LOG_LEVEL:INFO}