version: '3.7'
services:

  postgresql-service:
    image: postgres:9.4
    container_name: postgresql
    environment:
      POSTGRES_DATABASE: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - 5432:5432
    networks:
      - main_bridge


  elasticsearch-service:
    image: elasticsearch:8.7.1
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: "single-node"
      network.host: "0.0.0.0"
      transport.host: "0.0.0.0"
      xpack.security.enabled: "false"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    networks:
      - main_bridge

  kibana-service:
    image: kibana:8.7.1
    container_name: kibana
    depends_on:
      - elasticsearch-service
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    networks:
      - main_bridge

  logstash-service:
    image: logstash:8.7.1
    container_name: logstash
    volumes:
      - ./files/logstash/config/logstash.conf:/usr/share/logstash/config/logstash.conf
      - ./files/logstash/logs:/usr/share/logstash/logs
    command: logstash -f /usr/share/logstash/config/logstash.conf
    networks:
      - main_bridge

  prometheus-service:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./files/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - main_bridge

  prometheus-pushgateway-service:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - 9091:9091
    networks:
      - main_bridge

  grafana-service:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - 2999:3000
    networks:
      - main_bridge

  redis-service:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass redispassword --appendonly yes
    ports:
      - 6379:6379
    networks:
      - main_bridge

networks:
  main_bridge:
    driver: bridge