version: '3.7'
services:

  redis-service:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass redispassword --appendonly yes
    ports:
      - 6379:6379
    networks:
      - ntwrk

networks:
  ntwrk:
    driver: bridge